extends Node

@warning_ignore("unused_signal")
signal mailboxHoverOn(mailbox: Mailbox)
@warning_ignore("unused_signal")
signal mailboxHoverOff(mailbox: Mailbox)
@warning_ignore("unused_signal")
signal mailboxClosed()
@warning_ignore("unused_signal")
signal packageHoverOn(package: Package)
@warning_ignore("unused_signal")
signal packageHoverOff(package: Package)
@warning_ignore("unused_signal")
signal throwEnvelope(envelope: Node3D, thrower: Node3D, target: Node3D, throw_target_offset: Vector3)
@warning_ignore("unused_signal")
signal envelopeDelivered(deliverer: Node3D, envelope: Envelope, recipient: Node3D)
@warning_ignore("unused_signal")
signal packageDelivered(package: Package)
@warning_ignore("unused_signal")
signal packagePickedUp(package: Package)

@warning_ignore("unused_signal")
signal npcTargeting(npcs: Array)
@warning_ignore("unused_signal")
signal npcStopTarget()
@warning_ignore("unused_signal")
signal npcArrived(npc: NPC)
@warning_ignore("unused_signal")
signal npcKilled()

@warning_ignore("unused_signal")
signal levelComplete()
@warning_ignore("unused_signal")
signal advanceLevel()
@warning_ignore("unused_signal")
signal restartLevel()
@warning_ignore("unused_signal")
signal gameOver()
@warning_ignore("unused_signal")
signal tutorialClosed()
@warning_ignore("unused_signal")
signal playGame()

@warning_ignore("unused_signal")
signal playerSpawned(player: Player)
@warning_ignore("unused_signal")
signal playerStartThrow(sweetspotStart: float, sweetspotLength: float, timerLength: float)
@warning_ignore("unused_signal")
signal playerStopThrow()
